name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        mode: onefile
        out-file: EraClip
        windows-console-mode: disable

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: EraClip.exe